import { defineStore } from 'pinia'

export const products = [
  
      { id: 1,
        name: 'OLAY Regenerist Micro-Sculpting Cream',
        img: 'https://cloudinary.images-iherb.com/image/upload/f_auto,q_auto:eco/images/lay/lay19049/g/27.jpg',
        price: 999,
        type: 'skincare',
        descriptsion: 'Lorem ipsum, dolor sit amet consectetur adipisicing elit. Ex qui nisi nostrum perferendis nulla corporis laudantium quisquam, sunt quos aliquam mollitia at voluptates architecto sequi? Officiis repellendus ullam animi nulla.'
      },
      { id: 2,
        name: 'TYLENOL Paracetamol',
        img: 'https://punsuk.com/2623-6737-large_default/tylenol-paracetamol-500-100-.jpg',
        price: 140,
        type: 'Common-medicine',
        descriptsion: 'Lorem ipsum, dolor sit amet consectetur adipisicing elit. Ex qui nisi nostrum perferendis nulla corporis laudantium quisquam, sunt quos aliquam mollitia at voluptates architecto sequi? Officiis repellendus ullam animi nulla.'
       },
      { id: 3,
        name: 'Alcohol ALSOFF  70% Ethyl Alcohol Solution 60 ml.',
        img: 'https://www.makro.pro/_next/image?url=https%3A%2F%2Fimages.mango-prod.siammakro.cloud%2FSOURCE%2F698bfec7187d481b890e6ecd70f50f4f&w=640&q=75',
        price: 12,
        type: 'Common-medicine',
        descriptsion: 'Lorem ipsum, dolor sit amet consectetur adipisicing elit. Ex qui nisi nostrum perferendis nulla corporis laudantium quisquam, sunt quos aliquam mollitia at voluptates architecto sequi? Officiis repellendus ullam animi nulla.'
      },
        { id: 4,
        name: 'Hemomin Strawberry Flavoured egg with powder beverage  400g.',
        img: 'https://www.fascino.co.th/fasue-img/600/744/resize/2/3/235547_1__1.png',
        price: 849,
        type: 'protein',
        descriptsion: 'Lorem ipsum, dolor sit amet consectetur adipisicing elit. Ex qui nisi nostrum perferendis nulla corporis laudantium quisquam, sunt quos aliquam mollitia at voluptates architecto sequi? Officiis repellendus ullam animi nulla.'
      },
        { id: 5,
        name: 'Vistra acerola cherry ',
        img: 'https://www.fascino.co.th/fasue-img/600/744/resize/img_hq/154857-1.jpg',
        price: 632,
        type: 'vitamins',
        descriptsion: 'Lorem ipsum, dolor sit amet consectetur adipisicing elit. Ex qui nisi nostrum perferendis nulla corporis laudantium quisquam, sunt quos aliquam mollitia at voluptates architecto sequi? Officiis repellendus ullam animi nulla.'
      },
        { id: 6,
        name: 'NIVEA Extra Bright 10 Super Vitamins & Skin Foods Body Serum 320ml',
        img: 'https://img.lazcdn.com/g/p/e21f919bbcd52f1926c3456f25141739.jpg_720x720q80.jpg_.webp',
        price: 233,
        type: 'skincare',
        descriptsion: 'Lorem ipsum, dolor sit amet consectetur adipisicing elit. Ex qui nisi nostrum perferendis nulla corporis laudantium quisquam, sunt quos aliquam mollitia at voluptates architecto sequi? Officiis repellendus ullam animi nulla.'
      },
        { id: 7,
        name: 'Vistra Whey Protein Plus Powder ',
        img: 'https://www.fascino.co.th/fasue-img/600/744/resize/img_hq/201286-1.jpg',
        price: 463,
        type: 'protein',
        descriptsion: 'Lorem ipsum, dolor sit amet consectetur adipisicing elit. Ex qui nisi nostrum perferendis nulla corporis laudantium quisquam, sunt quos aliquam mollitia at voluptates architecto sequi? Officiis repellendus ullam animi nulla.'
      },
        { id: 8,
        name: 'Gaviscon Peppermint  150 ml ',
        img: 'https://down-th.img.susercontent.com/file/a5378c059e5e327b9983a82c91b23f8f',
        price: 265,
        type: 'Personal-medicine',
        descriptsion: 'Lorem ipsum, dolor sit amet consectetur adipisicing elit. Ex qui nisi nostrum perferendis nulla corporis laudantium quisquam, sunt quos aliquam mollitia at voluptates architecto sequi? Officiis repellendus ullam animi nulla.'
      },
        { id: 9,
        name: 'SK-ll GenOptics Aura Essence',
        img: 'https://image-optimizer-th.production.sephora-asia.net/images/product_images/closeup_1_Product_4979006085747-SKII-Genoptics-Ultraura-Essence-50ml_36986ee0365ce913965c2ef4f5e91dd1cebd0335_1702969981.png',
        price: 5300,
        type: 'skincare',
        descriptsion: 'Lorem ipsum, dolor sit amet consectetur adipisicing elit. Ex qui nisi nostrum perferendis nulla corporis laudantium quisquam, sunt quos aliquam mollitia at voluptates architecto sequi? Officiis repellendus ullam animi nulla.'
      },
        { id: 10,
        name: 'Vistra Gotu Kola Extract Plus Zinc',
        img: 'https://www.fascino.co.th/fasue-img/600/744/resize/2/1/214221.png',
        price: 243,
        type: 'vitamins',
        descriptsion: 'Lorem ipsum, dolor sit amet consectetur adipisicing elit. Ex qui nisi nostrum perferendis nulla corporis laudantium quisquam, sunt quos aliquam mollitia at voluptates architecto sequi? Officiis repellendus ullam animi nulla.'
      },
        { id: 11,
        name: 'Strepsils Honey Lemon 24s',
        img: 'https://st.bigc-cs.com/cdn-cgi/image/format=webp,quality=90/public/media/catalog/product/40/88/8850360310040/thumbnail/8850360310040_4.jpg',
        price:  24,
        type: 'Common-medicine',
        descriptsion: 'Lorem ipsum, dolor sit amet consectetur adipisicing elit. Ex qui nisi nostrum perferendis nulla corporis laudantium quisquam, sunt quos aliquam mollitia at voluptates architecto sequi? Officiis repellendus ullam animi nulla.'
       },
        { id: 12,
        name: 'ยาธาตุน้ำขาว ตรากระต่ายบิน 200 ml.',
        img: 'https://cx.lnwfile.com/_/cx/_raw/xo/m0/lg.jpg',
        price: 60,
        type: 'Common-medicine',
        descriptsion: 'Lorem ipsum, dolor sit amet consectetur adipisicing elit. Ex qui nisi nostrum perferendis nulla corporis laudantium quisquam, sunt quos aliquam mollitia at voluptates architecto sequi? Officiis repellendus ullam animi nulla.'
       },
        { id: 13,
        name: 'Centrum Silver 50+ Dietary Supplement ',
        img: 'https://www.fascino.co.th/fasue-img/600/744/resize/2/1/218073_1.png',
        price: 356,
        type: 'vitamins',
        descriptsion: 'Lorem ipsum, dolor sit amet consectetur adipisicing elit. Ex qui nisi nostrum perferendis nulla corporis laudantium quisquam, sunt quos aliquam mollitia at voluptates architecto sequi? Officiis repellendus ullam animi nulla.'
       },
        { id: 14,
        name: 'BEPANTHEN OINTMENT ',
        img: 'https://down-th.img.susercontent.com/file/2fe2ab2e2b9edd2366c83e96589e37d5',
        price: 174,
        type: 'Personal-medicine',
        descriptsion: 'Lorem ipsum, dolor sit amet consectetur adipisicing elit. Ex qui nisi nostrum perferendis nulla corporis laudantium quisquam, sunt quos aliquam mollitia at voluptates architecto sequi? Officiis repellendus ullam animi nulla.'
       },
        { id: 15,
        name: 'Royal-D Whey protein ',
        img: 'https://www.fascino.co.th/fasue-img/600/744/resize/img_hq/252288_1.jpg',
        price: 780,
        type: 'protein',
        descriptsion: 'Lorem ipsum, dolor sit amet consectetur adipisicing elit. Ex qui nisi nostrum perferendis nulla corporis laudantium quisquam, sunt quos aliquam mollitia at voluptates architecto sequi? Officiis repellendus ullam animi nulla.'
       },
        { id: 16,
        name: 'ENO Fruit Salt ',
        img: 'https://img.lazcdn.com/g/p/bbb1069aeb2f7d107005cf05ec8b1c92.jpg_720x720q80.jpg_.webp',
        price: 10,
        type: 'Personal-medicine',
        descriptsion: 'Lorem ipsum, dolor sit amet consectetur adipisicing elit. Ex qui nisi nostrum perferendis nulla corporis laudantium quisquam, sunt quos aliquam mollitia at voluptates architecto sequi? Officiis repellendus ullam animi nulla.'
       },
        { id: 17,
        name: 'Mega Ultrapro (Vanilla) ',
        img: 'https://www.fascino.co.th/fasue-img/600/744/resize/2/3/236306.png',
        price: 1794,
        type: 'protein',
        descriptsion: 'Lorem ipsum, dolor sit amet consectetur adipisicing elit. Ex qui nisi nostrum perferendis nulla corporis laudantium quisquam, sunt quos aliquam mollitia at voluptates architecto sequi? Officiis repellendus ullam animi nulla.' 
      },
        { id: 18,
        name: 'Lancôme New Advanced Génifique Serum ',
        img: 'https://image-optimizer-th.production.sephora-asia.net/images/product_images/closeup_3614272623545-GNF30ml_3622b22eb000ef8ed0101b2a8a5eafba9ef1eda0_1619266614.png',
        price: 3600,
        type: 'skincare',
        descriptsion: 'Lorem ipsum, dolor sit amet consectetur adipisicing elit. Ex qui nisi nostrum perferendis nulla corporis laudantium quisquam, sunt quos aliquam mollitia at voluptates architecto sequi? Officiis repellendus ullam animi nulla.'
       },
        { id: 19,
        name: 'Za True White EX Essence Lotion',
        img: 'https://down-th.img.susercontent.com/file/483ae61bd4524737a0e2386212399b20',
        price: 420,
        type: 'skincare',
        descriptsion: 'Lorem ipsum, dolor sit amet consectetur adipisicing elit. Ex qui nisi nostrum perferendis nulla corporis laudantium quisquam, sunt quos aliquam mollitia at voluptates architecto sequi? Officiis repellendus ullam animi nulla.'
       },
        { id: 20,
        name: 'Vistra Cla&L-Carnitine 1100MG Plus Vitamin E',
        img: 'https://www.fascino.co.th/fasue-img/600/744/resize/img_hq/224278-1.jpg',
        price: 643,
        type: 'vitamins',
        descriptsion: 'Lorem ipsum, dolor sit amet consectetur adipisicing elit. Ex qui nisi nostrum perferendis nulla corporis laudantium quisquam, sunt quos aliquam mollitia at voluptates architecto sequi? Officiis repellendus ullam animi nulla.'
       },
    ]

